<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ParkingSubmissionSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id' => 6,
                'submission_code' => 'FP202512023720',
                'customer_id' => 5,
                'vehicle_id' => 6,
                'submitted_by' => 5,
                'submission_date' => '2025-12-02',
                'duration_days' => 1,
                'purpose' => 'buat meeting',
                'id_card_image' => '1764661489_bca16010378d3438fbc2.jpg',
                'vehicle_image' => '1764661489_fa1de09cd3ba85cb0d78.jpg',
                'supporting_doc_image' => '1764661489_c98217b718af3bc009db.png',
                'operation_manager_approval' => 'pending',
                'operation_manager_id' => null,
                'operation_manager_notes' => null,
                'operation_manager_approval_date' => null,
                'parking_dept_approval' => 'pending',
                'parking_dept_id' => null,
                'parking_dept_notes' => null,
                'parking_dept_approval_date' => null,
                'quota_given' => null,
                'status' => 'submitted',
                'created_at' => '2025-12-02 00:44:49',
                'updated_at' => '2025-12-02 00:44:49',
            ],
            [
                'id' => 7,
                'submission_code' => 'FP202512020125',
                'customer_id' => 5,
                'vehicle_id' => 6,
                'submitted_by' => 5,
                'submission_date' => '2025-12-02',
                'duration_days' => 1,
                'purpose' => 'Untuk karaoke',
                'id_card_image' => '1764661602_9c5cb406ed9b9bdb4268.jpg',
                'vehicle_image' => '1764661602_c2d00727ae5032401bb9.png',
                'supporting_doc_image' => '1764661602_a2ec60e6bdd190501dfe.png',
                'operation_manager_approval' => 'pending',
                'operation_manager_id' => null,
                'operation_manager_notes' => null,
                'operation_manager_approval_date' => null,
                'parking_dept_approval' => 'pending',
                'parking_dept_id' => null,
                'parking_dept_notes' => null,
                'parking_dept_approval_date' => null,
                'quota_given' => null,
                'status' => 'submitted',
                'created_at' => '2025-12-02 00:46:42',
                'updated_at' => '2025-12-02 00:46:42',
            ],
            [
                'id' => 8,
                'submission_code' => 'FP202512028263',
                'customer_id' => 5,
                'vehicle_id' => 6,
                'submitted_by' => 5,
                'submission_date' => '2025-12-02',
                'duration_days' => 1,
                'purpose' => 'untuk ngeroom',
                'id_card_image' => '1764661620_3550a9e14d6b4d61bbcb.jpg',
                'vehicle_image' => '1764661620_0a56cb179d02ee468092.png',
                'supporting_doc_image' => '1764661620_86b5c7c979075d05899f.png',
                'operation_manager_approval' => 'pending',
                'operation_manager_id' => null,
                'operation_manager_notes' => null,
                'operation_manager_approval_date' => null,
                'parking_dept_approval' => 'pending',
                'parking_dept_id' => null,
                'parking_dept_notes' => null,
                'parking_dept_approval_date' => null,
                'quota_given' => null,
                'status' => 'submitted',
                'created_at' => '2025-12-02 00:47:00',
                'updated_at' => '2025-12-02 00:47:00',
            ],
            [
                'id' => 9,
                'submission_code' => 'FP202512051297',
                'customer_id' => 6,
                'vehicle_id' => 7,
                'submitted_by' => 9,
                'submission_date' => '2025-12-05',
                'duration_days' => 2,
                'purpose' => 'dua hari meeting',
                'id_card_image' => null,
                'vehicle_image' => null,
                'supporting_doc_image' => null,
                'operation_manager_approval' => 'pending',
                'operation_manager_id' => null,
                'operation_manager_notes' => null,
                'operation_manager_approval_date' => null,
                'parking_dept_approval' => 'pending',
                'parking_dept_id' => null,
                'parking_dept_notes' => null,
                'parking_dept_approval_date' => null,
                'quota_given' => null,
                'status' => 'submitted',
                'created_at' => '2025-12-04 22:02:30',
                'updated_at' => '2025-12-04 22:02:30',
            ],
        ];

        $this->db->table('parking_submissions')->insertBatch($data);
    }
}
